# -*- coding: utf-8 -*-
"""modelo_1_ols_rolling_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mriSY8kFc4ejCyMaTF5VlGrvNWRoOltL

# 🛢️ Modelo 1 v3: OLS Rolling + Term Structure do WTI
## Oil Majors NYSE × Preço do Petróleo (WTI)

---

### 🎯 O que muda em relação à v2?

A v2 já tinha filtro de regime macro (tendência do WTI) e de tendência por ação, mas a saída de uma posição continuava sendo só o z-score voltando ao normal (mean-reversion pura), com um stop-loss por baixo.

Essa versão adiciona um terceiro sinal — **term structure do petróleo (contango vs. backwardation)** — e usa ele de um jeito diferente dos outros dois: não é só um filtro de entrada, é também um **motivo pra manter a posição aberta** mesmo quando o z-score já "normalizou".

### 🔧 As 2 mudanças desta versão

1. **Term structure via EIA (contratos futuros 1º a 4º mês)** — `backwardation` (contrato próximo mais caro que o distante) soma pro lado bullish; `contango` soma pro lado bearish. Isso vira o terceiro voto num **score de convicção** (regime macro + tendência da ação + term structure, de -3 a +3).
2. **"Hold override" com trailing stop** — se o score de convicção continua fortemente a favor da posição (≥ 2 ou ≤ -2), o modelo **ignora o sinal de saída por reversão** e deixa a posição correr. Só sai por stop-loss (perda desde a entrada) ou por **trailing stop** (queda desde o pico atingido durante a posição) — isso protege o lucro acumulado sem cortar a posição no primeiro sinal de "voltou ao normal".

Isso é literalmente a sua ideia: *"se o futuro de longo prazo está valorizando, pode indicar que manter a posição é uma boa ideia"* — só que aplicada com um limite de segurança (trailing stop), pra não virar "deixa correr pra sempre e devolve tudo se a tendência virar".

### ⚠️ Nota importante sobre dados

O `yfinance` não entrega term structure — só o contrato de vencimento mais próximo (`CL=F`). Este notebook usa a **API gratuita da EIA** (U.S. Energy Information Administration), que publica oficialmente os preços de settlement do NYMEX para os contratos WTI do 1º ao 4º mês de vencimento (séries `RCLC1`-`RCLC4`).

**Isso cobre contango/backwardation de curto prazo (até ~4 meses à frente) — não o vencimento de 12-24 meses.** Pra isso seria necessário uma fonte paga (CME/Nasdaq Data Link/Bloomberg). É a limitação honesta desta abordagem: captura bem o "aperto de oferta imediato", mas não a expectativa de preço de longuíssimo prazo.

**Você precisa de uma chave gratuita da EIA** pra rodar essa parte — cadastro em 1 minuto em https://www.eia.gov/opendata/, a chave chega por e-mail na hora. Cole ela na célula "Configuração EIA" abaixo. Se você rodar sem chave, o notebook não quebra — ele só desativa o filtro de term structure e o v3 fica equivalente ao v2 (mais o trailing stop).

Este notebook reconstrói o pipeline completo (v1 baseline, v2 híbrido, v3 com term structure) pra comparar os três lado a lado no mesmo período de teste.

---

## 📦 Passo 0: Instalação das Bibliotecas
"""
import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns
import statsmodels.api as sm
from statsmodels.regression.rolling import RollingOLS
from scipy import stats
import requests
import warnings
warnings.filterwarnings('ignore')

# Configurações visuais
plt.style.use('seaborn-v0_8-darkgrid')
sns.set_palette('husl')
plt.rcParams['figure.figsize'] = (14, 6)
plt.rcParams['font.size'] = 11

print('✅ Bibliotecas carregadas com sucesso!')

"""## 🏭 Passo 2: Definindo o Universo de Ativos

Mesma lógica das versões anteriores — separamos por elo da cadeia produtiva (Upstream / Refino / Midstream).
"""

# =============================================================================
# UNIVERSO DE ATIVOS - apenas listagem primária e direta na NYSE
# =============================================================================

ATIVOS_POR_SEGMENTO = {
    'Upstream': {
        'tickers': ['XOM', 'CVX', 'COP', 'OXY', 'EOG', 'DVN', 'CTRA', 'MUR'],
        'multiplicador_risco': 1.0,
        'descricao': 'Alta sensibilidade ao WTI. Sinal direto e forte.'
    },
    'Refino': {
        'tickers': ['MPC', 'PSX', 'VLO'],
        'multiplicador_risco': 0.6,
        'descricao': 'Relação não-linear. Crack spread importa mais que preço bruto.'
    },
    'Midstream': {
        'tickers': ['KMI', 'WMB'],
        'multiplicador_risco': 0.3,
        'descricao': 'Baixa sensibilidade ao WTI. Receita majoritariamente contratada.'
    }
}

TICKER_PETROLEO = 'CL=F'

TODOS_TICKERS = [t for seg in ATIVOS_POR_SEGMENTO.values() for t in seg['tickers']]

TICKER_PARA_SEGMENTO = {}
for seg, dados in ATIVOS_POR_SEGMENTO.items():
    for t in dados['tickers']:
        TICKER_PARA_SEGMENTO[t] = seg

print('📋 Universo de ativos:')
for seg, dados in ATIVOS_POR_SEGMENTO.items():
    print(f"  {seg}: {dados['tickers']}")
    print(f"    → {dados['descricao']}")
print(f'\n🛢️ Petróleo: {TICKER_PETROLEO}')

"""## 📥 Passo 3: Download e Tratamento dos Dados (Ações + WTI Spot)

Mesmo tratamento das versões anteriores: série contínua do WTI, remoção de saltos de rollover, log-retornos, alinhamento temporal.
"""

# =============================================================================
# DOWNLOAD DE DADOS
# =============================================================================

GRANULARIDADE = '1d'
DATA_INICIO = '2015-01-01'
DATA_FIM = (pd.Timestamp.today() + pd.Timedelta(days=1)).strftime('%Y-%m-%d')

print('📥 Baixando dados... (pode demorar 1-2 minutos)')

print(f'  → Baixando {len(TODOS_TICKERS)} ações ({GRANULARIDADE})...')
raw_acoes = yf.download(
    TODOS_TICKERS,
    start=DATA_INICIO,
    end=DATA_FIM,
    interval=GRANULARIDADE,
    auto_adjust=True,
    progress=False
)
precos_acoes = raw_acoes['Close'].copy()

print('  → Baixando WTI (CL=F) - sempre diário para consistência...')
raw_wti = yf.download(
    TICKER_PETROLEO,
    start=DATA_INICIO,
    end=DATA_FIM,
    interval='1d',
    auto_adjust=True,
    progress=False
)
preco_wti = raw_wti['Close'].squeeze()

print(f'\n✅ Download concluído!')
print(f'   Ações: {precos_acoes.shape[0]} períodos × {precos_acoes.shape[1]} ativos')
print(f'   WTI: {len(preco_wti)} dias')
print(f'   Período: {precos_acoes.index[0]} → {precos_acoes.index[-1]}')

# =============================================================================
# TRATAMENTO E NORMALIZAÇÃO DOS DADOS
# =============================================================================

retorno_wti_bruto = preco_wti.pct_change()
mascara_rollover = retorno_wti_bruto.abs() > 0.15
n_rollovers = mascara_rollover.sum()
print(f'⚙️ Saltos de rollover detectados no WTI: {n_rollovers}')

retorno_wti_limpo = retorno_wti_bruto.copy()
retorno_wti_limpo[mascara_rollover] = np.nan

if GRANULARIDADE == '1h':
    precos_acoes_diario = precos_acoes.resample('1D').last().dropna(how='all')
    print('⏰ Ações agregadas de horário para diário para alinhar com WTI')
else:
    precos_acoes_diario = precos_acoes.copy()

log_ret_acoes = np.log(precos_acoes_diario / precos_acoes_diario.shift(1))

log_ret_wti = np.log(preco_wti / preco_wti.shift(1))
log_ret_wti[mascara_rollover] = np.nan

precos_acoes_diario.index = pd.to_datetime(precos_acoes_diario.index).normalize()
preco_wti.index = pd.to_datetime(preco_wti.index).normalize()
log_ret_acoes.index = pd.to_datetime(log_ret_acoes.index).normalize()
log_ret_wti.index = pd.to_datetime(log_ret_wti.index).normalize()

df = log_ret_acoes.join(log_ret_wti.rename('WTI'), how='inner')
df = df.dropna(subset=['WTI'])

limite_nulos = 0.20
colunas_validas = [c for c in df.columns
                   if c == 'WTI' or df[c].isna().mean() < limite_nulos]
df = df[colunas_validas]
df = df.fillna(0)

acoes_disponiveis = [c for c in df.columns if c != 'WTI']

precos_nivel = precos_acoes_diario.reindex(df.index)[acoes_disponiveis].ffill()
preco_wti_nivel = preco_wti.reindex(df.index).ffill()

print(f'\n📊 Dataset final:')
print(f'   Período: {df.index[0].date()} → {df.index[-1].date()}')
print(f'   Observações: {len(df)}')
print(f'   Ativos válidos: {acoes_disponiveis}')

"""## 🛢️ Passo 4 (NOVO): Configuração EIA — Term Structure do WTI

Cole sua chave gratuita da EIA na variável abaixo. Cadastro: https://www.eia.gov/opendata/ (a chave chega por e-mail, sem custo).

Se você deixar em branco ou a chave for inválida, o notebook **não quebra** — ele avisa e segue com o filtro de term structure desativado (equivalente a `regime_term = 0` em todos os dias).
"""

# =============================================================================
# CONFIGURAÇÃO DA CHAVE DA EIA
# =============================================================================

EIA_API_KEY = 'sQ8JJIqJ0QexQlWJ6ROTfJD4iVuD9zNpGbtW3IIh'  # cadastro gratuito em https://www.eia.gov/opendata/

def fetch_eia_series(series_id, api_key, data_inicio, data_fim):
    # Busca uma série diária de futuros de petróleo da API da EIA, paginando se necessário.
    dados = []
    offset = 0
    tamanho_pagina = 5000
    while True:
        url = (
            'https://api.eia.gov/v2/petroleum/pri/fut/data/'
            f'?api_key={api_key}'
            '&frequency=daily'
            '&data[0]=value'
            f'&facets[series][]={series_id}'
            f'&start={data_inicio}'
            f'&end={data_fim}'
            '&sort[0][column]=period'
            '&sort[0][direction]=asc'
            f'&offset={offset}'
            f'&length={tamanho_pagina}'
        )
        resp = requests.get(url, timeout=30)
        resp.raise_for_status()
        payload = resp.json()['response']['data']
        if not payload:
            break
        dados.extend(payload)
        if len(payload) < tamanho_pagina:
            break
        offset += tamanho_pagina

    serie = pd.DataFrame(dados)
    serie['period'] = pd.to_datetime(serie['period'])
    serie = serie.set_index('period')['value'].astype(float).sort_index()
    return serie

print('🔑 Chave EIA configurada.' if EIA_API_KEY and EIA_API_KEY != 'COLE_SUA_CHAVE_AQUI'
      else '⚠️ Chave EIA ainda não configurada — cole sua chave na variável EIA_API_KEY acima.')

"""### Contango vs. Backwardation

- **Contrato 1** (`RCLC1`): vencimento mais próximo (~1 mês)
- **Contrato 4** (`RCLC4`): vencimento mais distante disponível de graça na EIA (~4 meses)

Calculamos o spread percentual entre eles: `(Contrato4 - Contrato1) / Contrato1`

- Spread **negativo** → contrato próximo mais caro → **backwardation** → tilt bullish (mercado precificando aperto de oferta agora)
- Spread **positivo** → contrato distante mais caro → **contango** → tilt bearish/neutro (mercado precificando folga de oferta)

Suavizamos com uma média móvel de 10 dias pra não reagir a ruído diário, e usamos uma pequena "zona morta" (±0,5%) pra não ficar trocando de regime por variação irrelevante.
"""

# =============================================================================
# BUSCA E PROCESSAMENTO DO TERM STRUCTURE
# =============================================================================

TERM_STRUCTURE_DISPONIVEL = False

try:
    if EIA_API_KEY and EIA_API_KEY != 'COLE_SUA_CHAVE_AQUI':
        rclc1 = fetch_eia_series('RCLC1', EIA_API_KEY, DATA_INICIO, DATA_FIM)
        rclc4 = fetch_eia_series('RCLC4', EIA_API_KEY, DATA_INICIO, DATA_FIM)
        TERM_STRUCTURE_DISPONIVEL = True
        print(f'✅ Term structure EIA carregado: {len(rclc1)} obs (contrato 1), {len(rclc4)} obs (contrato 4)')
    else:
        print('⚠️ EIA_API_KEY não configurada — o filtro de term structure ficará desativado (regime_term = 0).')
except Exception as e:
    print(f'⚠️ Falha ao buscar dados da EIA: {e}')
    print('   O notebook vai continuar sem o filtro de term structure (regime_term ficará neutro).')

JANELA_SUAVIZACAO_TERMO = 10
LIMIAR_TERMO = 0.005  # zona morta de 0.5%

if TERM_STRUCTURE_DISPONIVEL:
    termo = pd.DataFrame({'c1': rclc1, 'c4': rclc4}).dropna()
    termo['spread_pct'] = (termo['c4'] - termo['c1']) / termo['c1']
    termo['spread_suave'] = termo['spread_pct'].rolling(JANELA_SUAVIZACAO_TERMO).mean()

    regime_term_raw = pd.Series(0, index=termo.index)
    regime_term_raw[termo['spread_suave'] < -LIMIAR_TERMO] = 1    # backwardation -> bullish
    regime_term_raw[termo['spread_suave'] > LIMIAR_TERMO] = -1    # contango -> bearish/neutro

    regime_term = regime_term_raw.reindex(df.index, method='ffill').fillna(0)

    print('\n🛢️ Regime de term structure (contrato 1 vs. contrato 4):')
    print(f"   Backwardation (tilt bullish): {(regime_term == 1).mean():.1%} dos dias")
    print(f"   Contango (tilt bearish/neutro): {(regime_term == -1).mean():.1%} dos dias")
    print(f"   Zona morta / sem dado: {(regime_term == 0).mean():.1%} dos dias")

    # --- Visualização ---
    fig, ax = plt.subplots(figsize=(14, 4))
    ax.plot(termo.index, termo['spread_pct'] * 100, color='gray', alpha=0.4, linewidth=0.8, label='Spread bruto (%)')
    ax.plot(termo.index, termo['spread_suave'] * 100, color='#e67e22', linewidth=1.5,
            label=f'Spread suavizado ({JANELA_SUAVIZACAO_TERMO}d)')
    ax.axhline(0, color='black', linewidth=0.8)
    ax.axhline(LIMIAR_TERMO * 100, color='gray', linewidth=0.7, linestyle=':')
    ax.axhline(-LIMIAR_TERMO * 100, color='gray', linewidth=0.7, linestyle=':')
    ax.set_ylabel('Spread Contrato4 vs Contrato1 (%)')
    ax.set_title('Term Structure do WTI — Contango (>0) vs Backwardation (<0)', fontsize=13, fontweight='bold')
    ax.legend(loc='upper left', fontsize=9)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()
else:
    regime_term = pd.Series(0, index=df.index)
    print('ℹ️ regime_term = 0 em todos os dias (term structure desativado).')

"""## 📐 Passo 5: OLS Estático (Linha de Base)"""

resultados_ols = {}
X = sm.add_constant(df['WTI'])

print('📐 OLS Estático - Resultados por Ação:')
print('-' * 70)
print(f'{"Ticker":<8} {"Segmento":<12} {"Alpha":<10} {"Beta":<10} {"R²":<8} {"p-value β":<10}')
print('-' * 70)

for ticker in acoes_disponiveis:
    y = df[ticker].dropna()
    X_alinhado = X.loc[y.index]

    modelo = sm.OLS(y, X_alinhado).fit()

    alpha = modelo.params['const']
    beta = modelo.params['WTI']
    r2 = modelo.rsquared
    pval = modelo.pvalues['WTI']

    seg = TICKER_PARA_SEGMENTO.get(ticker, '?')
    resultados_ols[ticker] = {
        'alpha': alpha, 'beta': beta, 'r2': r2,
        'pvalue': pval, 'modelo': modelo, 'segmento': seg
    }

    sig = '✅' if pval < 0.05 else '❌'
    print(f'{ticker:<8} {seg:<12} {alpha:+.4f}    {beta:+.4f}    {r2:.3f}    {pval:.4f} {sig}')

"""## 🪟 Passo 6: Rolling-Window OLS (janela de 60 dias)"""

JANELA_ROLLING = 60

print(f'🪟 Calculando Rolling Beta com janela de {JANELA_ROLLING} dias...')

betas_rolling = pd.DataFrame(index=df.index)
alphas_rolling = pd.DataFrame(index=df.index)
residuos_rolling = pd.DataFrame(index=df.index)

X_roll = sm.add_constant(df['WTI'])

for ticker in acoes_disponiveis:
    y = df[ticker]

    modelo_roll = RollingOLS(
        endog=y,
        exog=X_roll,
        window=JANELA_ROLLING,
        min_nobs=30
    ).fit()

    betas_rolling[ticker] = modelo_roll.params['WTI']
    alphas_rolling[ticker] = modelo_roll.params['const']

    retorno_esperado = (alphas_rolling[ticker] +
                        betas_rolling[ticker] * df['WTI'])
    residuos_rolling[ticker] = y - retorno_esperado

print('✅ Rolling Beta calculado!')

"""## 🧭 Passo 7: Filtro de Regime Macro — Tendência do WTI (igual à v2)

Cruzamento EMA 50 × EMA 200 no preço do WTI.
"""

EMA_CURTA = 50
EMA_LONGA = 200

ema_curta_wti = preco_wti_nivel.ewm(span=EMA_CURTA, min_periods=EMA_CURTA).mean()
ema_longa_wti = preco_wti_nivel.ewm(span=EMA_LONGA, min_periods=EMA_LONGA).mean()

regime_macro = pd.Series(0, index=df.index)
regime_macro[ema_curta_wti > ema_longa_wti] = 1
regime_macro[ema_curta_wti < ema_longa_wti] = -1
regime_macro[ema_longa_wti.isna()] = 0

n_alta = (regime_macro == 1).sum()
n_baixa = (regime_macro == -1).sum()
print(f'🧭 Regime macro (WTI EMA{EMA_CURTA} × EMA{EMA_LONGA}):')
print(f'   Dias em Alta:  {n_alta} ({n_alta/len(df):.1%})')
print(f'   Dias em Baixa: {n_baixa} ({n_baixa/len(df):.1%})')

"""## 📈 Passo 8: Filtro de Tendência da Própria Ação (igual à v2)

Preço vs. média móvel de 100 dias.
"""

JANELA_TENDENCIA_ACAO = 100

sma_acao = precos_nivel.rolling(JANELA_TENDENCIA_ACAO, min_periods=JANELA_TENDENCIA_ACAO).mean()

tendencia_acao = pd.DataFrame(0, index=df.index, columns=acoes_disponiveis)
tendencia_acao[precos_nivel > sma_acao] = 1
tendencia_acao[precos_nivel < sma_acao] = -1
tendencia_acao[sma_acao.isna()] = 0

print(f'📈 Tendência individual calculada (SMA {JANELA_TENDENCIA_ACAO} dias) para {len(acoes_disponiveis)} ativos.')

"""## 📰 Passo 8.5: Indicador de Notícia (novo na v4)

Os três filtros anteriores (regime macro, tendência da ação, term structure) são todos
derivados de **preço** — por construção só reagem depois que o mercado se mexeu. O indicador
de notícia tenta ler a causa antes do efeito.

A base vem de um CSV externo (`jornal, manchete, data, hora, sinal`) com o sinal em [-1, 1] já
atribuído; notícias irrelevantes ficam com o sinal vazio e são descartadas. O módulo
`news_signal.py` faz o corte de sessão (16h de NY), agrega o dia e aplica o decaimento
exponencial. A rubrica completa de classificação está documentada no topo daquele arquivo.

**O voto é relativo, não absoluto.** A pergunta não é "a notícia está altista?" — o
noticiário de petróleo é estruturalmente altista (guerra e sanção empurram o preço para
cima), e no nível absoluto esse voto ficava `+1` em 82% dos dias, virando uma constante
somada ao score em vez de informação. O voto compara o noticiário de hoje com a média móvel
dele mesmo (60 pregões), do mesmo jeito que o z-score do resíduo faz com a OLS: `+1` só
quando está **mais** altista que o próprio normal.

Se o CSV ou o módulo não estiverem presentes (rodando no Colab sem subir os arquivos),
o notebook **não quebra** — segue com `regime_noticia = 0` em todos os dias, exatamente como
faz quando a chave da EIA está ausente.
"""

# =============================================================================
# INDICADOR DE NOTÍCIA
# =============================================================================

ARQUIVO_NOTICIAS = 'noticias_pontuadas.csv'
NOTICIAS_DISPONIVEIS = False

try:
    import news_signal
    regime_noticia = news_signal.carregar_regime(ARQUIVO_NOTICIAS, df.index)
    NOTICIAS_DISPONIVEIS = True
except Exception as e:
    print(f'⚠️ Indicador de notícia desativado: {e}')
    print('   O notebook vai continuar sem o 4º voto (regime_noticia ficará neutro).')
    regime_noticia = pd.Series(0, index=df.index)

"""## 📏 Passo 9: Position Sizing por Volatilidade Realizada (igual à v2)"""

JANELA_VOL = 21
VOL_ALVO_ANUALIZADA = 0.25
ESCALA_MIN, ESCALA_MAX = 0.3, 1.5

vol_realizada = df[acoes_disponiveis].rolling(JANELA_VOL).std() * np.sqrt(252)
escala_vol = (VOL_ALVO_ANUALIZADA / (vol_realizada + 1e-6)).clip(ESCALA_MIN, ESCALA_MAX)
escala_vol = escala_vol.fillna(1.0)

print(f'📏 Escala de volatilidade calculada (alvo: {VOL_ALVO_ANUALIZADA:.0%} a.a., janela {JANELA_VOL}d).')

"""## 📡 Passo 10: Geração de Sinais — v1, v2, v3 e v4

- **v1**: mean-reversion pura (baseline original)
- **v2**: v1 + filtro de regime macro + tendência da ação + vol scaling + stop-loss
- **v3**: v2 + term structure como 3º voto no score de convicção + **hold override com trailing stop** (deixa a posição correr quando a convicção estrutural continua forte, em vez de sair no primeiro sinal de reversão)
- **v4**: v3 + **indicador de notícia** como 4º voto (score passa a variar de -4 a +4)

O **score de convicção** em v3 é a soma dos 3 filtros (`regime_macro + tendencia_acao + regime_term`), variando de -3 a +3:
- `score ≤ -2`: pelo menos 2 dos 3 sinais concordam em baixa estrutural → só aí um short é permitido, e um long ignora o override
- `score ≥ +2`: pelo menos 2 dos 3 sinais concordam em alta estrutural → um long em aberto ignora o sinal de saída por reversão (mas continua protegido por stop-loss e trailing stop)
"""

# =============================================================================
# PARÂMETROS DE SINAL (compartilhados entre v1, v2 e v3)
# =============================================================================

JANELA_ZSCORE = 20
JANELA_RESIDUO = 5
LIMIAR_ENTRADA = 1.5
LIMIAR_SAIDA = 0.5
STOP_LOSS_PCT = 0.12
TRAILING_STOP_PCT = 0.08   # novo em v3: protege lucro quando o hold override está ativo

# Convicção mínima para confirmar um regime. Na v3 são 3 votos (-3..+3) e o corte é 2.
# Na v4 são 4 votos (-4..+4): manter 2 afrouxa o critério (passa a bastar 2 de 4).
#
# Rodamos as duas calibrações no CSV de exemplo (Sharpe out-of-sample, v3 = -0.67):
#   LIMIAR_SCORE_V4 = 2  ->  -0.69   (322 posições ticker-dia divergindo da v3)
#   LIMIAR_SCORE_V4 = 3  ->  -0.60   (1963 divergências)
# Mas o controle com 3 e SEM notícia nenhuma dá -0.64 com 1738 divergências: ou seja, a
# maior parte do ganho do corte 3 vem do próprio aperto do critério, não da notícia.
# Mantemos 2 como padrão porque é o único valor em que "sem CSV de notícia" reproduz a v3
# exatamente — o que torna o efeito da notícia isolável. Trocar para 3 é uma decisão de
# calibração separada, que merece grid search só no período de treino.
LIMIAR_SCORE_V4 = 2

zscores = pd.DataFrame(index=df.index, columns=acoes_disponiveis, dtype=float)
for ticker in acoes_disponiveis:
    residuo_acum = residuos_rolling[ticker].rolling(JANELA_RESIDUO).sum()
    media_res = residuo_acum.rolling(JANELA_ZSCORE).mean()
    std_res = residuo_acum.rolling(JANELA_ZSCORE).std()
    zscores[ticker] = (residuo_acum - media_res) / (std_res + 1e-10)

print('✅ Z-scores calculados.')

# =============================================================================
# SINAL v1: MEAN-REVERSION PURA (baseline)
# =============================================================================

posicoes_brutas_v1 = pd.DataFrame(index=df.index, columns=acoes_disponiveis, dtype=float)
posicoes_ajustadas_v1 = pd.DataFrame(index=df.index, columns=acoes_disponiveis, dtype=float)

for ticker in acoes_disponiveis:
    seg = TICKER_PARA_SEGMENTO.get(ticker, 'Upstream')
    mult_risco = ATIVOS_POR_SEGMENTO[seg]['multiplicador_risco']
    zscore = zscores[ticker]

    posicao = pd.Series(0.0, index=df.index)
    posicao_atual = 0
    for i in range(len(df)):
        z = zscore.iloc[i]
        if pd.isna(z):
            posicao.iloc[i] = 0
            continue
        if posicao_atual == 0:
            if z < -LIMIAR_ENTRADA:
                posicao_atual = 1
            elif z > LIMIAR_ENTRADA:
                posicao_atual = -1
        elif posicao_atual == 1:
            if z > -LIMIAR_SAIDA:
                posicao_atual = 0
        elif posicao_atual == -1:
            if z < LIMIAR_SAIDA:
                posicao_atual = 0
        posicao.iloc[i] = posicao_atual

    posicoes_brutas_v1[ticker] = posicao
    posicoes_ajustadas_v1[ticker] = posicao * mult_risco

print('📡 Sinal v1 (baseline) gerado.')

# =============================================================================
# SINAL v2: REGIME MACRO + TENDÊNCIA DA AÇÃO + VOL SCALING + STOP-LOSS
# =============================================================================

posicoes_brutas_v2 = pd.DataFrame(index=df.index, columns=acoes_disponiveis, dtype=float)
posicoes_ajustadas_v2 = pd.DataFrame(index=df.index, columns=acoes_disponiveis, dtype=float)

for ticker in acoes_disponiveis:
    seg = TICKER_PARA_SEGMENTO.get(ticker, 'Upstream')
    mult_risco = ATIVOS_POR_SEGMENTO[seg]['multiplicador_risco']
    zscore = zscores[ticker]
    tend_acao = tendencia_acao[ticker]
    preco_ticker = precos_nivel[ticker]

    posicao = pd.Series(0.0, index=df.index)
    posicao_atual = 0
    preco_entrada = np.nan

    for i in range(len(df)):
        z = zscore.iloc[i]
        reg_macro = regime_macro.iloc[i]
        reg_acao = tend_acao.iloc[i]
        preco_hoje = preco_ticker.iloc[i]

        if pd.isna(z):
            posicao.iloc[i] = 0
            continue

        baixa_confirmada = (reg_macro == -1) and (reg_acao == -1)

        if posicao_atual == 0:
            if z < -LIMIAR_ENTRADA and not baixa_confirmada:
                posicao_atual = 1
                preco_entrada = preco_hoje
            elif z > LIMIAR_ENTRADA and baixa_confirmada:
                posicao_atual = -1
                preco_entrada = preco_hoje
        elif posicao_atual == 1:
            perda = (preco_hoje / preco_entrada) - 1 if preco_entrada and not np.isnan(preco_entrada) else 0
            if z > -LIMIAR_SAIDA or perda < -STOP_LOSS_PCT:
                posicao_atual = 0
                preco_entrada = np.nan
        elif posicao_atual == -1:
            perda = 1 - (preco_hoje / preco_entrada) if preco_entrada and not np.isnan(preco_entrada) else 0
            if z < LIMIAR_SAIDA or perda < -STOP_LOSS_PCT:
                posicao_atual = 0
                preco_entrada = np.nan

        posicao.iloc[i] = posicao_atual

    posicoes_brutas_v2[ticker] = posicao
    escala = escala_vol[ticker]
    posicoes_ajustadas_v2[ticker] = posicao * mult_risco * escala

print('📡 Sinal v2 gerado.')

# =============================================================================
# SINAL v3: v2 + TERM STRUCTURE + HOLD OVERRIDE COM TRAILING STOP
# =============================================================================

posicoes_brutas_v3 = pd.DataFrame(index=df.index, columns=acoes_disponiveis, dtype=float)
posicoes_ajustadas_v3 = pd.DataFrame(index=df.index, columns=acoes_disponiveis, dtype=float)
overrides_long = {t: 0 for t in acoes_disponiveis}
overrides_short = {t: 0 for t in acoes_disponiveis}

for ticker in acoes_disponiveis:
    seg = TICKER_PARA_SEGMENTO.get(ticker, 'Upstream')
    mult_risco = ATIVOS_POR_SEGMENTO[seg]['multiplicador_risco']
    zscore = zscores[ticker]
    tend_acao = tendencia_acao[ticker]
    preco_ticker = precos_nivel[ticker]

    posicao = pd.Series(0.0, index=df.index)
    posicao_atual = 0
    preco_entrada = np.nan
    preco_pico = np.nan  # maior preço desde a entrada (long) ou menor preço desde a entrada (short)

    for i in range(len(df)):
        z = zscore.iloc[i]
        reg_macro = regime_macro.iloc[i]
        reg_acao = tend_acao.iloc[i]
        reg_termo = regime_term.iloc[i]
        preco_hoje = preco_ticker.iloc[i]

        if pd.isna(z):
            posicao.iloc[i] = 0
            continue

        # score de convicção: -3 (bearish total) a +3 (bullish total)
        score = reg_macro + reg_acao + reg_termo
        baixa_confirmada = score <= -2
        alta_confirmada = score >= 2

        if posicao_atual == 0:
            if z < -LIMIAR_ENTRADA and not baixa_confirmada:
                posicao_atual = 1
                preco_entrada = preco_hoje
                preco_pico = preco_hoje
            elif z > LIMIAR_ENTRADA and baixa_confirmada:
                posicao_atual = -1
                preco_entrada = preco_hoje
                preco_pico = preco_hoje

        elif posicao_atual == 1:
            preco_pico = preco_hoje if np.isnan(preco_pico) else max(preco_pico, preco_hoje)
            perda_entrada = (preco_hoje / preco_entrada) - 1
            queda_do_topo = 1 - (preco_hoje / preco_pico)

            sinal_reversao_neutro = z > -LIMIAR_SAIDA
            # convicção estrutural de alta ainda forte -> ignora a saída por reversão e deixa correr
            sai_por_reversao = sinal_reversao_neutro and not alta_confirmada
            if sinal_reversao_neutro and alta_confirmada:
                overrides_long[ticker] += 1

            if sai_por_reversao or perda_entrada < -STOP_LOSS_PCT or queda_do_topo > TRAILING_STOP_PCT:
                posicao_atual = 0
                preco_entrada = np.nan
                preco_pico = np.nan

        elif posicao_atual == -1:
            preco_pico = preco_hoje if np.isnan(preco_pico) else min(preco_pico, preco_hoje)
            perda_entrada = 1 - (preco_hoje / preco_entrada)
            retracao_do_fundo = (preco_hoje / preco_pico) - 1

            sinal_reversao_neutro = z < LIMIAR_SAIDA
            sai_por_reversao = sinal_reversao_neutro and not baixa_confirmada
            if sinal_reversao_neutro and baixa_confirmada:
                overrides_short[ticker] += 1

            if sai_por_reversao or perda_entrada < -STOP_LOSS_PCT or retracao_do_fundo > TRAILING_STOP_PCT:
                posicao_atual = 0
                preco_entrada = np.nan
                preco_pico = np.nan

        posicao.iloc[i] = posicao_atual

    posicoes_brutas_v3[ticker] = posicao
    escala = escala_vol[ticker]
    posicoes_ajustadas_v3[ticker] = posicao * mult_risco * escala

print('📡 Sinal v3 gerado.')
print('\n🔁 Dias em que o "hold override" segurou a posição em vez de sair por reversão:')
for t in acoes_disponiveis:
    print(f'  {t}: longs seguradas em {overrides_long[t]}d | shorts seguradas em {overrides_short[t]}d')

# =============================================================================
# SINAL v4: v3 + INDICADOR DE NOTÍCIA COMO 4º VOTO
# =============================================================================
# Cópia do loop da v3 com uma única mudança de lógica: o score de convicção passa a somar
# `reg_noticia` e vai de -4 a +4. Com o CSV de notícias ausente, `regime_noticia` é 0 em
# todos os dias e a v4 fica numericamente idêntica à v3 (com LIMIAR_SCORE_V4 = 2).

posicoes_brutas_v4 = pd.DataFrame(index=df.index, columns=acoes_disponiveis, dtype=float)
posicoes_ajustadas_v4 = pd.DataFrame(index=df.index, columns=acoes_disponiveis, dtype=float)

for ticker in acoes_disponiveis:
    seg = TICKER_PARA_SEGMENTO.get(ticker, 'Upstream')
    mult_risco = ATIVOS_POR_SEGMENTO[seg]['multiplicador_risco']
    zscore = zscores[ticker]
    tend_acao = tendencia_acao[ticker]
    preco_ticker = precos_nivel[ticker]

    posicao = pd.Series(0.0, index=df.index)
    posicao_atual = 0
    preco_entrada = np.nan
    preco_pico = np.nan

    for i in range(len(df)):
        z = zscore.iloc[i]
        reg_macro = regime_macro.iloc[i]
        reg_acao = tend_acao.iloc[i]
        reg_termo = regime_term.iloc[i]
        reg_noticia = regime_noticia.iloc[i]
        preco_hoje = preco_ticker.iloc[i]

        if pd.isna(z):
            posicao.iloc[i] = 0
            continue

        # score de convicção: -4 (bearish total) a +4 (bullish total)
        score = reg_macro + reg_acao + reg_termo + reg_noticia
        baixa_confirmada = score <= -LIMIAR_SCORE_V4
        alta_confirmada = score >= LIMIAR_SCORE_V4

        if posicao_atual == 0:
            if z < -LIMIAR_ENTRADA and not baixa_confirmada:
                posicao_atual = 1
                preco_entrada = preco_hoje
                preco_pico = preco_hoje
            elif z > LIMIAR_ENTRADA and baixa_confirmada:
                posicao_atual = -1
                preco_entrada = preco_hoje
                preco_pico = preco_hoje

        elif posicao_atual == 1:
            preco_pico = preco_hoje if np.isnan(preco_pico) else max(preco_pico, preco_hoje)
            perda_entrada = (preco_hoje / preco_entrada) - 1
            queda_do_topo = 1 - (preco_hoje / preco_pico)

            sinal_reversao_neutro = z > -LIMIAR_SAIDA
            sai_por_reversao = sinal_reversao_neutro and not alta_confirmada

            if sai_por_reversao or perda_entrada < -STOP_LOSS_PCT or queda_do_topo > TRAILING_STOP_PCT:
                posicao_atual = 0
                preco_entrada = np.nan
                preco_pico = np.nan

        elif posicao_atual == -1:
            preco_pico = preco_hoje if np.isnan(preco_pico) else min(preco_pico, preco_hoje)
            perda_entrada = 1 - (preco_hoje / preco_entrada)
            retracao_do_fundo = (preco_hoje / preco_pico) - 1

            sinal_reversao_neutro = z < LIMIAR_SAIDA
            sai_por_reversao = sinal_reversao_neutro and not baixa_confirmada

            if sai_por_reversao or perda_entrada < -STOP_LOSS_PCT or retracao_do_fundo > TRAILING_STOP_PCT:
                posicao_atual = 0
                preco_entrada = np.nan
                preco_pico = np.nan

        posicao.iloc[i] = posicao_atual

    posicoes_brutas_v4[ticker] = posicao
    escala = escala_vol[ticker]
    posicoes_ajustadas_v4[ticker] = posicao * mult_risco * escala

dias_divergentes = (posicoes_brutas_v4 != posicoes_brutas_v3).sum().sum()
print(f'\n📡 Sinal v4 gerado (LIMIAR_SCORE_V4 = {LIMIAR_SCORE_V4}).')
print(f'   Posições ticker-dia em que a v4 divergiu da v3: {dias_divergentes}')

"""## 🔬 Passo 11: Backtest Comparativo — v1 vs v2 vs v3 vs Buy & Hold

Mesmas regras de rigor: execução defasada (`shift(1)`), custo de transação, separação treino/teste 60/40. Todos os filtros (regime macro, tendência da ação, term structure) usam apenas dado disponível até o dia anterior — sem look-ahead bias em nenhuma camada.
"""

# =============================================================================
# BACKTEST WALK-FORWARD COM SEPARAÇÃO TREINO/TESTE
# =============================================================================

CUSTO_POR_TRADE = 0.001

corte = int(len(df) * 0.60)
idx_teste = df.index[corte:]

print(f'📅 Período de Treino: {df.index[0].date()} → {df.index[corte-1].date()}')
print(f'📅 Período de Teste:  {df.index[corte].date()} → {df.index[-1].date()}')

def calcula_retorno_portfolio(posicoes_ajustadas):
    retornos_estrategia = pd.DataFrame(index=df.index)
    for ticker in acoes_disponiveis:
        posicao_defasada = posicoes_ajustadas[ticker].shift(1).fillna(0)
        retorno_bruto = posicao_defasada * df[ticker]
        mudanca_posicao = posicao_defasada.diff().abs()
        custo = mudanca_posicao * CUSTO_POR_TRADE
        retornos_estrategia[ticker] = retorno_bruto - custo
    return retornos_estrategia.mean(axis=1)

retorno_portfolio_v1 = calcula_retorno_portfolio(posicoes_ajustadas_v1)
retorno_portfolio_v2 = calcula_retorno_portfolio(posicoes_ajustadas_v2)
retorno_portfolio_v3 = calcula_retorno_portfolio(posicoes_ajustadas_v3)
retorno_portfolio_v4 = calcula_retorno_portfolio(posicoes_ajustadas_v4)
retorno_bh = df[acoes_disponiveis].mean(axis=1)

ret_v1_test = retorno_portfolio_v1.loc[idx_teste]
ret_v2_test = retorno_portfolio_v2.loc[idx_teste]
ret_v3_test = retorno_portfolio_v3.loc[idx_teste]
ret_v4_test = retorno_portfolio_v4.loc[idx_teste]
ret_bh_test = retorno_bh.loc[idx_teste]

def calcular_metricas(retornos, rf_diaria=0.0):
    retorno_acum = (1 + retornos).cumprod()
    retorno_total = retorno_acum.iloc[-1] - 1
    n_anos = len(retornos) / 252
    retorno_anual = (1 + retorno_total) ** (1/n_anos) - 1
    vol_anual = retornos.std() * np.sqrt(252)
    sharpe = (retorno_anual - rf_diaria*252) / (vol_anual + 1e-10)

    pico = retorno_acum.cummax()
    drawdown = (retorno_acum - pico) / pico
    max_dd = drawdown.min()
    calmar = retorno_anual / abs(max_dd) if max_dd != 0 else np.nan

    return {
        'Retorno Total': f'{retorno_total:.1%}',
        'Retorno Anual': f'{retorno_anual:.1%}',
        'Volatilidade Anual': f'{vol_anual:.1%}',
        'Sharpe Ratio': f'{sharpe:.2f}',
        'Max Drawdown': f'{max_dd:.1%}',
        'Calmar Ratio': f'{calmar:.2f}'
    }

m_v1 = calcular_metricas(ret_v1_test)
m_v2 = calcular_metricas(ret_v2_test)
m_v3 = calcular_metricas(ret_v3_test)
m_v4 = calcular_metricas(ret_v4_test)
m_bh = calcular_metricas(ret_bh_test)

def imprime_tabela(titulo, metricas):
    m1, m2, m3, m4, mbh = metricas
    print(titulo)
    print('=' * 114)
    print(f'{"Métrica":<22} {"v1 (baseline)":>16} {"v2 (híbrido)":>16} {"v3 (+ term struct)":>20} '
          f'{"v4 (+ notícia)":>18} {"Buy & Hold":>16}')
    print('-' * 114)
    for k in m1:
        print(f'{k:<22} {m1[k]:>16} {m2[k]:>16} {m3[k]:>20} {m4[k]:>18} {mbh[k]:>16}')
    print('=' * 114)

imprime_tabela('\n📊 RESULTADOS DO BACKTEST (período de teste out-of-sample):',
               (m_v1, m_v2, m_v3, m_v4, m_bh))

# Segunda tabela, só onde existe notícia. Sem ela a comparação v3 vs v4 é diluída:
# antes da primeira manchete o voto de notícia é 0 e a v4 é idêntica à v3 por
# construção. O corte sai da própria série (não de uma data no código), então
# continua correto se a base de notícias mudar.
dias_com_noticia = regime_noticia[regime_noticia != 0].index
idx_noticia = idx_teste[idx_teste >= dias_com_noticia[0]] if len(dias_com_noticia) else []

if len(idx_noticia) > 60:
    metricas_noticia = tuple(calcular_metricas(r.loc[idx_noticia]) for r in
                             (retorno_portfolio_v1, retorno_portfolio_v2, retorno_portfolio_v3,
                              retorno_portfolio_v4, retorno_bh))
    imprime_tabela(f'\n📰 MESMO BACKTEST, SÓ NO PERÍODO COM NOTÍCIA '
                   f'({idx_noticia[0].date()} → {idx_noticia[-1].date()}, '
                   f'{len(idx_noticia)} pregões):', metricas_noticia)
    print('   É aqui que a v4 difere da v3 de fato — na tabela acima ela é idêntica')
    print(f'   à v3 em {len(idx_teste) - len(idx_noticia)} dos {len(idx_teste)} pregões de teste.')
else:
    print('\nℹ️ Período com notícia curto demais para uma segunda tabela.')

print('\n⚠️  Lembrete: Resultados passados não garantem resultados futuros!')

"""## 📊 Passo 12: Visualização do Backtest"""

# =============================================================================
# VISUALIZAÇÃO COMPARATIVA DO BACKTEST
# =============================================================================

fig, axes = plt.subplots(2, 1, figsize=(14, 10))

ax1 = axes[0]
acum_v1 = (1 + ret_v1_test).cumprod()
acum_v2 = (1 + ret_v2_test).cumprod()
acum_v3 = (1 + ret_v3_test).cumprod()
acum_v4 = (1 + ret_v4_test).cumprod()
acum_bh = (1 + ret_bh_test).cumprod()

ax1.plot(acum_v4, label='v4 (+ indicador de notícia)', color='#c0392b', linewidth=2.2)
ax1.plot(acum_v3, label='v3 (+ term structure + hold override)', color='#e67e22', linewidth=1.8, linestyle='--')
ax1.plot(acum_v2, label='v2 (regime + tendência + vol)', color='#2ecc71', linewidth=1.6, linestyle='--')
ax1.plot(acum_v1, label='v1 (mean-reversion baseline)', color='#9b59b6', linewidth=1.3, linestyle=':')
ax1.plot(acum_bh, label='Buy & Hold Ações', color='#3498db', linewidth=1.6, linestyle='-.')
ax1.set_ylabel('Valor do Portfólio (R$1 inicial)', fontsize=11)
ax1.set_title('Curva de Patrimônio — Período de Teste (Out-of-Sample)', fontsize=13, fontweight='bold')
ax1.legend(fontsize=9)
ax1.grid(True, alpha=0.3)

ax2 = axes[1]
pico_v1 = acum_v1.cummax(); dd_v1 = (acum_v1 - pico_v1) / pico_v1
pico_v2 = acum_v2.cummax(); dd_v2 = (acum_v2 - pico_v2) / pico_v2
pico_v3 = acum_v3.cummax(); dd_v3 = (acum_v3 - pico_v3) / pico_v3
pico_v4 = acum_v4.cummax(); dd_v4 = (acum_v4 - pico_v4) / pico_v4
pico_bh = acum_bh.cummax(); dd_bh = (acum_bh - pico_bh) / pico_bh

ax2.fill_between(dd_v4.index, dd_v4, 0, alpha=0.45, color='#c0392b', label='v4')
ax2.fill_between(dd_v3.index, dd_v3, 0, alpha=0.35, color='#e67e22', label='v3')
ax2.fill_between(dd_v2.index, dd_v2, 0, alpha=0.25, color='#2ecc71', label='v2')
ax2.fill_between(dd_v1.index, dd_v1, 0, alpha=0.15, color='#9b59b6', label='v1')
ax2.fill_between(dd_bh.index, dd_bh, 0, alpha=0.15, color='#3498db', label='Buy & Hold')
ax2.set_ylabel('Drawdown (%)', fontsize=11)
ax2.set_title('Drawdown Máximo — Queda do Pico ao Vale', fontsize=13, fontweight='bold')
ax2.legend(fontsize=9)
ax2.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y:.0%}'))
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

"""## 📰 Sobre a v4 (indicador de notícia)

A v4 é a v3 com um 4º voto no score de convicção, vindo de um CSV externo de notícias já
pontuadas em [-1, 1]. **O CSV que acompanha o repo (`noticias_exemplo.csv`) é sintético e
serve só para exercitar o encanamento** — as manchetes são ilustrativas (fonte `EXEMPLO`),
cobrem apenas 2024-2025 e portanto ~5% do período de teste. Qualquer diferença de métrica
entre v3 e v4 hoje é ruído, não evidência: o que está validado é o caminho do dado, não o
sinal.

O que já está garantido por construção:
- **Sem look-ahead**: notícia publicada após as 16h de NY só conta para o pregão seguinte, e
  o backtest ainda aplica `shift(1)` por cima.
- **Degradação limpa**: sem o CSV, a v4 reproduz a v3 número a número (0 divergências) —
  é o teste que prova que o wiring não mexeu em mais nada.

Para virar sinal de verdade falta a base real de notícias e o classificador automático
(a rubrica que ele vai seguir já está escrita no topo de `news_signal.py`).

## 📋 Conclusões e Limitações do Modelo v3

### ✅ O que a v3 adiciona sobre a v2:
- Um terceiro sinal independente (term structure) que captura expectativa de oferta/demanda de curto prazo — informação que nem o preço nem o beta ao WTI capturam diretamente
- Um mecanismo de "deixar o lucro correr" quando a convicção estrutural continua forte, em vez de sair automaticamente no primeiro sinal de reversão
- Um trailing stop que dá um limite de segurança a essa decisão — não é "aposta cega na tendência", é "aposta na tendência com stop"

### ⚠️ Limitações honestas:
1. **A term structure gratuita (EIA) só cobre até ~4 meses.** Não testa diretamente sua hipótese original de "futuro de 12-24 meses valorizando" — isso exigiria uma fonte paga.
2. **Mais um parâmetro sensível:** o limiar de convicção (`score ≤ -2` / `≥ +2`) e o trailing stop (8%) foram escolhidos por heurística, não otimizados no treino.
3. **O hold override pode manter uma posição perdedora por mais tempo** se o score ficar "preso" em convicção forte enquanto o preço ainda não reverteu — o trailing stop limita isso, mas não elimina.
4. **Ainda sem hedge direto contra o petróleo** — mesma limitação da v2.

### 🔧 Próximos passos naturais:
- Se os resultados da v3 justificarem, testar uma fonte paga de term structure (Nasdaq Data Link/CME) para cobrir 12-24 meses e testar a hipótese original de verdade
- Grid search do limiar de convicção e do trailing stop, só no período de treino
- Testar o v3 em diferentes subperíodos (não só o corte 60/40) para checar se o ganho é robusto ou específico deste teste
"""